# Site settings
title: "Veronica Solinas"
email: veronica.solinas@libero.it
description: > # this means to ignore newlines until "baseurl:"
Composer and videomaker
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://veronicasolinas.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
